// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	     
		int N = Integer.parseInt(args[0]); //the number of times we'll check Math.random(). received via input
		int i = 0; //index
		double r; 
		int greater = 0; // > 0.5
		int lessorequal = 0; // <= 0.5
		while (i < N) {
			r = Math.random(); //saves a random number (0.0-1.0) inside r 
			if (r > 0.5) //checks if the number is greater/ less or equal to 0.5
				greater ++;
			else
				lessorequal ++;
			i ++;
		}

		System.out.println("> 0.5: " + greater);
		System.out.println("<= 0.5: " + lessorequal); 

	 	if (greater != 0 && lessorequal!= 0) { //checks the special case (can't divide a number by 0)

			if (greater > lessorequal) //condition in order to get the ratio 
				System.out.println((double) lessorequal / greater);
			else
				System.out.println((double) greater / lessorequal);
		} 
	}
}
